apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:5AfnmLVcEOLx,iv:sFsNXa8X98PS7H0u6sLjUe7VOEKtUTgTcnOiargt0cs=,tag:XcZqxhsRhfpy2QKygVCAqA==,type:str]
    password: ENC[AES256_GCM,data:JywyeHCJo1s=,iv:Pn0sAvRZ59NWswsf0YPP+hpMJF0ylw+imbsUkrk7ISQ=,tag:d/RMvnlV5RFXuStoqSZGFQ==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1vcrqvlyc26ffpjme3253zk2zf20skl532xdxj2yc5290ut0vu4gq592zfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhakdOdlQ0SFBRZkNINE54
            eEtxWmpLTlBxOEVXb0h3bXNEUnpuakpuSWg0CjArR0d3Mkd1bjAydm0yUFpmcW5m
            dnJiWFFrWHdsbitncFoyNzJEQnQxcVEKLS0tIHpKbWNTanR0cWxhbFlpUWwwdW0w
            YWZicUsxU3JwQlVlMUpSVjc5NUEvMFkKRfmXHRLZOHMIyzELZqlGT4gbwo2BRj3v
            8+97RMOXeUYeAs/ME6geOgptrOBxRRNz+qVE+q/+QTAyr+MktOCUCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T02:15:51Z"
    mac: ENC[AES256_GCM,data:xS5x2HNYK17eINO3aDGtOfx7C1Hl9+LdyzU6HoaEZwQjMbRAjttGRvDWeNEpfSUnl9lHxKFjRaPQDcMQbuM4YBQdr7RNDEntqC+LhFbvXBgVRZLMvtcN1cQUunFZqPKhY2r83YmK2gvp5/rJzlnGg+yG9611PPXnZbHY9OdcQiU=,iv:4uhmC/UDolUeGIoUckcXf0UatXD2gPJRy5u4kW6+gew=,tag:ohfQFkWxHpKTqbHWw0FjkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
