apiVersion: v1
kind: Secret
metadata:
    name: postgres-shortener-secret
    namespace: default
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:q/dbGOkJMTfF,iv:6Erx1J3ZJIF0fClCCI8ngkE9FEPysWOHQD7A8j+Ugb0=,tag:Kkdr9heuKU0JvDTVFj+BYQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WDNf08YHPwc=,iv:lBOFjHZO6sqLj0EiV9UqiN6MFYPNCBhj3SumX9IskCU=,tag:ulW0Oqiv09DCauhLCiZtvQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1vcrqvlyc26ffpjme3253zk2zf20skl532xdxj2yc5290ut0vu4gq592zfx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeG8rZjVJK2xGeFR2bU1G
            TitiYThMdkZmcjdLWWpBdzM2WjU4WkVvYXc4CmZaWXJPanhGZVhxQU9kSjZ5Qkoy
            U1gvZ3N6OEliK2NxNnJnZzl4d1loamsKLS0tIHhOalEvQmFZWVFuV1ZNYTRVanNR
            czFOMjJZazVLb3ZwOG56LzI3Q0xNa2MKO5bqu1F87mu7TPcQUj1wfx91YrvSLAHb
            ek88UK/dBetsFVLgT+gNMxrj5TeKU5gja6AlDqX5McgFdXZVOZMAjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T02:15:51Z"
    mac: ENC[AES256_GCM,data:BSsFKdyUrxAQ+B+NbQ1/LVFVwa6Y/Xi5e544eMCEzKF5g0KUdOFUsLo3aCAAb7spRVYWiXSXZAubWk++08axEKHzmtF/GG3gJXBc+hBf/FVbhLynlK5aWNcNRg4zgctCfhacgQQCab4xT1veo1mDl7xE7DOIQh0NN5+XrwOWq2I=,iv:wxIJ6iXnWPqDg3Hz8ypXCcNbXJhRrqIbpmcEL7VasVg=,tag:H3MMfWSrKwBKR6cSiww5Ug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
